// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gordan0410/common/dto"
	"github.com/gordan0410/common/log"
	"project_template/internal/config"
	"project_template/internal/delivery/http"
	"project_template/internal/delivery/http/handler"
	"project_template/internal/delivery/http/middleware"
	"project_template/internal/delivery/http/router"
	"project_template/internal/usecase"
)

// Injectors from wire.go:

func InitializeApplication(version dto.VersionInfo, logger *log.CommonLogger, envConfig *config.EnvConfig, masterDBConfig *config.DatabaseConfig, redisConfig *config.RedisConfig) *Application {
	middlewareI := middleware.NewMiddleware()
	healthUsecase := usecase.NewHealthUsecase()
	heartbeatHandlerI := handler.NewHeartbeatHandler(logger, healthUsecase)
	routerI := router.NewRouter(middlewareI, heartbeatHandlerI)
	httpApiServer := http.NewHttpApiServer(logger, middlewareI, routerI)
	application := NewApplication(envConfig, logger, httpApiServer)
	return application
}

// wire.go:

type Application struct {
	//version    *common_dto.VersionInfo
	envConfig  *config.EnvConfig
	logger     *log.CommonLogger
	httpServer *http.HttpApiServer
}

func NewApplication(

	envConfig *config.EnvConfig,
	logger *log.CommonLogger,
	httpServer *http.HttpApiServer,
) *Application {
	return &Application{

		envConfig:  envConfig,
		logger:     logger,
		httpServer: httpServer,
	}
}
